version: "3" 

services:
  graphql:
    container_name: graphql
    build:
      context: ./graphql
    ports:
      - 4000:4000
    links:
      - "mongo:mongodb"
    networks: 
      - mongo-compose-network

  apache:
      container_name: php
      image: php:7.2-apache
      ports:
        - 8000:80
      volumes:
        - ./ui/:/var/www/html
      links:
        - "graphql:graphql"
      networks: 
      - mongo-compose-network

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mongo-compose-network

  mongo-express:
    container_name: mongo_express
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks: 
      - mongo-compose-network


networks:
  mongo-compose-network:
    driver: bridge


volumes:
  mongodata:
